### ISSUE TITLE
Python2 - Plugin SyntaxError: comma cannot follow *args.

### ISSUE THREAD

**Issue by ldunhamci** [mikemalinowski/massimo#1]
https://github.com/mikemalinowski/massimo/blob/ace7fea294387871d8b4550755414d3b6a99c8e7/massimo/plug-ins/massimo_runtime.py#L679C32-L679C32
https://github.com/mikemalinowski/massimo/blob/ace7fea294387871d8b4550755414d3b6a99c8e7/massimo/plug-ins/massimo_runtime.py#L682C32-L682C32

EDIT: Context, issue is in Maya 2020 py 2.7.11. 
Py3 shouldnt have this issue.

**Comment by mikemalinowski** [comment]
Thanks ldunham - i have merged in your fix
